# Site settings
baseURL = "https://riohackerspace.github.io/"
languageCode = "pt-BR"
title = "Rio Hacker Space"
theme = "split"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy 2018 - Rio Hacker Space"

[params]

  # Metadata for search engines and social sharing
  name = "Rio Hacker Space"
  description = "Pagina oficial do Rio Hacker Space"
  shareImage = "images/riohackerspace-logo.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Content
  [params.content]
    name = "Rio Hacker Space"
    tagline = "Espaço colaborativo para hackers & makers na cidade maravilhosa"
    bio = ""

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/riohackerspace-logo.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = ""

      [[params.links.list1.link]]
        text = ""
        url = "#"

      [[params.links.list1.link]]
        text = ""
        url = "#"

      [[params.links.list1.link]]
        text = ""
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = ""

      [[params.links.list2.link]]
        text = ""
        url = "#"

      [[params.links.list2.link]]
        text = ""
        url = "#"

      [[params.links.list2.link]]
        text = ""
        url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Network"

      [[params.links.list3.link]]
        text = "Fabulosa"
        url = "http://fabulosa.cc/"

      [[params.links.list3.link]]
        text = "Mente Binária"
        url = "http://www.mentebinaria.com.br"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
